### ISSUE TITLE
Dependencies check failed for mod_quizgame

### ISSUE THREAD

**Issue by Junosprite007** [xow/moodle-mod_quizgame#79]
I'm getting this error when attempting to upgrade moodle. It's forcing to stop using this plugin. 

Dependencies check failed for mod_quizgame
You must solve all the plugin requirements before proceeding to install this Moodle version!

Is this plugin going to receive support in the future?

**Comment by sbourget** [comment]
Hi,

I'm going to need a bit more information in order to troubleshoot the error.  
Which version of the plugin are you using?  
Also which version of Moodle are you trying to upgrade to?

At present the latest version of the plugin works on Moodle 4.0 and it is currently planned to be updated for Moodle 4.1 once it is released this fall.

Thanks!

**Comment by Junosprite007** [comment]
It looks like this plugin stopped working with Moodle 3.11. I fixed it by upgrading to Moodle 4, and now I cannot reproduce the error. Sorry for the delayed response.

**Comment by sbourget** [comment]
Thanks for the feedback
